### ISSUE TITLE
[Balanss] Kvantitāte un kvalitāte

### ISSUE THREAD

**Issue by xEdgeA** [xVelns/IronCountry#11]
vajag izmaiņas un asap. paspēlēju 3h un sapratu, ka tagadējā sistēma nekam neder. viegli abuse. un sapratu kapēc supercar broken. Vajag pārtaisīt lietu daudzumu kabatā un mašīnā. 100 dēļi uz rokas lien, bet smagā mašīnā tik 75, ļoti loģiski, attiecīgi nav jēgas no mašīnu kapacitātes, ja izdevīgāk ir ātrāk pārvietoties pa lielceļu.

Samainīt visas lietas, lai aizņem bagāžniekā 1 slotu.

Inventory kabatas kapacitāte kā piemērs zāģētavai:

- 10 koks > 10 zāģēts koks > 10 dēļi
Attiecīgi pacelt cenu dēlim uz $20. Smagās mašīnas bagāžas kapacitāti samazināt uz 70. Pārdošanas vietu nedaudz atklātāku, pieejamāku, lai var piebraukt tuvu ar smago un ērti pārdot pa 10 ņemot ārā no mašīnas. Gala rezultātā izīrējot smago no darba kopā mēs uz pārdošanu vestu 80 dēļus, kas kopsummā būtu $1600 par braucienu.

Vēl notestēju auduma gatavošanu, tur arī viss skābi. Vilna aizņem 0.1 slotu mašīnā, attiecīgi var iekrāmēt 4000 vilnu darba busiņā. Maksimālais daudzums ko var turēt rokās ir 60, bet savācamais daudzums ir 40.
Ieteikums kabatas kapacitātei:
-10 vilna > 20 neapstrādāts audums > 10 drēbes, lai nav jāmaina pārstrādes konversija.
Cenu pacelt drēbēm uz $20 par gabalu. Uz pārdošanu vestu 50 gab. ar darba mašīnu, kas kopsummā būtu $1000 par braucienu.

Nav testētas pārējās darba vietas, bet es domāju ir vienkārši pielietot tādu pašu sistēmu realistiskākai un balansētākai ekonomikai.

**Comment by xVelns** [comment]
Iepakoto dēļu daudzu rokās ir ticis nomainīts no **100** uz **25**.
Smagās automašīnas vieta ir samazināta no **150 KG**, uz **70 KG**.
Viens iepakots dēlis sver **1KG = 70 dēļi darba auto.**
**Sapakoto dēļu cena ir mazliet palielināta.**

> 10 koks > 10 zāģēts koks > 10 dēļi

Šis tehniski nestrādātu, ņemot vērāt daudz maz reālos dzīves faktorus, ka apstrādājot koku, biezums/lielums etc. vienmēr samazinās, tādējādi nevar saņemt 1:1 attiecībā.

**Tika pievienotas vilnas smagums.
Drēbju cenas tika mazliet palielinātas.**

Pārmērīgas lielas cenas netiek ieviestas jo pilsēta neapgrozas tikai ap naudu. Un tāpat kā arī dzīvē, ir jāstrādā daudz, lai tik pie kārotā.

Ja ir kādi jautājumi par šo, droši varam to apspriest, xEdgeA
