### ISSUE TITLE
QoL izmaiņas

### ISSUE THREAD

**Issue by xEdgeA** [xVelns/IronCountry#12]
Izmēģinot vākšanas darbus ar pārstrādi nonācu pie dažām idejām, lai uzlabotu tos.
**Problēmas/Neskaidrības:** Tātad... 
**Drēbnieks** Vilna iet inventory 60, bet maksimālais savācamais daudzums ir 40. Skripts uzskata, ka maksimālais inventory daudzums ir 40, bet patiesībā ir 60. Tas pats pie pārstrādes no nepārstrādāta auduma uz drēbēm. Inventory limits drēbēm 60, bet skripts uzskata ka 40. Mašīnas bagāžniekā viena drēbe sver 2kg/sloti.
**Miesniekam** pagaidām šādu neskaidrību nav, bet inventory lien 100 filejas, mašīnā tik 1 par slotu.
**Mežstrādniekam** ar izmaiņām ir nekvalitātīva vākšanas un pārstrādāšanas procedūra. Var savākt 20 koku, 20 sazāģēt, bet tik 5 sazāģetu koku var pārvērst dēļos un tad ir sasniegts limits, attiecīgi ir ātri jāmūk prom, lai netiek skaitīts nost sazāģētais koks, jo vairs nav vietas somā priekš dēļiem.

**[Ieteikums]** Izmainīt visu darba sistēmu šajās 3 darba jomās. Lai mašīnas bagāžas nodalījums būtu nepieciešams un attiecībā pret inventory būtu tuvāk patiesībai un arī paliktu 1 lieta 1 slots. Realistiskāka inventory kapacitāte. Zāģētāva: Inventory maksimālais savācamais koks 10, sazāģētais koks 10, dēļi 10. Ar to ka dēļi inventory lien tikai 10, pārtstrāde no sazāģēta koka uz dēļiem 1:1, tb: 10 sazāģēta koka pārvēršana 10 dēļos. Attiecīgi varēs neskatīties uz rokām, kas ar ko pārvadā dēļus. Varbūt dēļi ir metru gari tik, attiecīgi var arī ielīst sedana bagāžniekā, bet līdz ar to ka aptuveni tur ir 16 sloti, izdevīgi tas nebūtu. Busiņā jau ap 40 slotiem, tuvāk patiesībai piekrāmēt busu ar dēļiem un daudziem patiks iespēja iegādāties busiņus darba vajadzībām, lai nav jāizīrē darba auto.
Miesnieks: Inventory maksimālais savācamais daudzums - vista 10 / beigta vista 10 / vistas fileja 10. Arī izmainīt to, ka beigtas vistas pārvēršana ir 1:1, tb: 10 beigtas vistas ir 10 filejas.
Drēbnieks: Inventory maksimālais savācamais daudzums - Vilna 10 / Neapstrādāts audums 10 / Drēbes 10. Izmainīt vilnas pārstrādi uz neapstrādātu audumu 1:1. Izmainīt neapstrādāta auduma pārstrādi uz drēbēm 1:1.  Izmainīt drēbes svaru uz 1kg/slotu.

Pārdošanas cenu uz jūsu ieskatiem. Bet vajag līdzvērtīgas iespējas visiem darbiem, lai spēlētājam nav jāstrādā tikai tur, kur sanāk vairāk nopelnīt.
Noklusējuma nododamais daudzums katrā darbā ar izīrējamo darba mašīnu un inventory pēc izmaiņām:

- Gaterī: 80

- Humpalās: 50

- Gaļas veikalā: 80

Ņemot vērā, ka drēbniekam ir jābrauc nedaudz tuvāk pēc vilnas nekā pārējos darbos, tad tur gala summa -10/15% attiecībā pret pārējiem.

**Comment by xEdgeA** [comment]
Vēl vajadzētu iespēju aizslēgt/atslēgt no darba izīrēto mašīnu, lai ar vieglu sirdi var pārstrādāt un neraizēties par to, ka kāds tev velk ārā materiālus un krāmē savā mašīnā.

**Comment by xVelns** [comment]
Itemus daudzums salabots attiecīgiem cipariem.
Drēbes gabals sver **1KG** gabalā.

Vistas filejas daudzums un limits kabatās no **100 pārlikts uz 50**.
Mazliet **palielināta** pārdošanas cena filejām.
Auto paņemšana palielināta no **150 uz 500.**

Mežstrādnieka auto cena palielināta no **150 uz 750**.
Nebūs 1:1 attiecība, un darbs ir jāveic ar savu darba auto.

Darba auto svara daudzums tiek līdzsvarots uz visu to auto kategoriju un šobrīd nav iespējams regulēt atsevisķi, tādēji ir ievērots balanss.

Auto nevar aizslēgt jo netiek piešķira Īpašnieka status.
Īpašnieka status netiek piešķirts jo tad darba auto varētu ielikt/izņemt no garāžas un izmantot/labot/upgreidot kā viens sirds grib.
