### ISSUE TITLE
on duty / off duty / Un kruiza kontrole utt

### ISSUE THREAD

**Issue by Marsmelo21** [xVelns/IronCountry#13]
https://forum.fivem.net/t/esx-on-off-duty-script/108174
Varētu šo ielikt mentiem lai varētu iet duty un iziet no ta.
https://www.gta5-mods.com/scripts/basiccruisecontrol
Šeit kruiza kontrole ja vēlas tādu.
https://www.gta5-mods.com/scripts/shield-mod
https://www.gta5-mods.com/scripts/drive-modes
Nezinu vai kadam no jums šitads ir bet kaut cik butu vieglak kruķīt handlingus ja vajadzes.
https://www.gta5-mods.com/scripts/death-animations
Miršanas animācija vairak padaritu mor rly ka cilveks nomirst lenam.
https://forum.fivem.net/t/release-police-backup-sets-waypoint-clean-layout-display-1-0/189439
https://www.gta5-mods.com/scripts/dashcam-v
Kamera jeb video reģistrators ja nu noderes.

**Comment by xVelns** [comment]
Tikai 1 no šiem skriptim var tikt ielikts iekšā pašā serverī un tas ir no Fivem foruma.

Viss pārējais kas nāk no GTA5-mods lielākoties neder FiveM jo viņš izmantot citus pamatus.

To On/Off Duty es biju jau apskatījis. Doma laba, bet ne šobrīd vajadzīga.
Kapēc? - Pilsētā šobrīd jau ir sūdzības par to, ka nav policistu/ātro un ka tādi parādas lielos daudzumos tikai apmācību dēļ un tad pazūd. Tapēc šis šobrīd netiks ieviests, bet paldies par ieteikumu.
