### ISSUE TITLE
Ludzu sito mahas mod Latvijas masinu

### ISSUE THREAD

**Issue by LIARsss** [xVelns/IronCountry#14]
https://www.lcpdfr.com/files/file/14872-latvian-police-texture-pack/

**Comment by LIARsss** [comment]
ludzu ari omegu pievienojat severi

**Comment by progamerminecraftxd** [comment]
Es atbalstu šo ieteikumu, jo tomēr mēs visi rpojam Latviju.

**Comment by progamerminecraftxd** [comment]
Omegai varētu iedot arī karabīni un granātmetēju kaut kādu.

**Comment by LIARsss** [comment]
piekritu

**Comment by xVelns** [comment]
Izmanto paraugu lai veiktu ieteikumu.
Nebūs Latvijas auto Los Santosā.
