### ISSUE TITLE
degvielas kanna

### ISSUE THREAD

**Issue by RazzieYT** [xVelns/IronCountry#2]
Vajag degvielas kannu ieviest, jo bieži pusceļā beidzas degviela un nezini ko darīt vairs.

**Comment by goodylv** [comment]
Nu labi jā, bet taču ielejot pilnu bāku, tu vari nobraukt lielu gabalu. Neseko līdzi degvielas dačikam?

**Comment by xVelns** [comment]
Lūdzu izmanto < Code > esošās veidnes, lai veiktu pieprasījumu.
Kā arī Degvielas kannas jau ir pieejamas pilsētā, nāksies tev viņas tikai atrast. :)
