### ISSUE TITLE
Slēdzamās druvis

### ISSUE THREAD

**Issue by Elperty** [xVelns/IronCountry#20]
Iedot iespēju LSGD atslēgt LSPD durvis un attiecīgi LSPD atslēgt LSGD durvis <3

**Comment by xVelns** [comment]
**Lūdzu sekot veidlapas izkārtojumam nākamreiz.**

Un tas nav iespējams, jo durvis tiek reģistrētas uz darbinieka amata.
Police = LSPD.
Ambulance = LSGD.
Apvienot to diemžēl nevar.
