### ISSUE TITLE
Modified Street Names w/ Postal Numbers

### ISSUE THREAD

**Issue by Gamediti** [xVelns/IronCountry#21]
Nemapot mapi uz sektoru veidu u.c ,  valsts orgāniem butu vieglāk orentēties u.c pēc manam domam.

https://forum.fivem.net/t/release-modified-street-names-w-postal-numbers/8717

**Comment by xVelns** [comment]
Lūgums sekot veidnes paraugam.

Karti var uzlikt client sided ja vēlies, lai cilvēkiem nēbūtu jāforso virsū karte ko nevēlas vai izmanto citu custom.

No pasta kodiem jēgu diemžēl neredzu.
