### ISSUE TITLE
[Ieteikums] Mehāniķa darbs

### ISSUE THREAD

**Issue by Letiix** [xVelns/IronCountry#3]
Ieteikums nomainīt mehāniķa 'NPC' darba uzsākšanas pogu uz kādu citu, no tagadējās 'DELETE' pogas, jo uz tās ir spēlētāju saraksts. Pievienot jaunu darba automašīnu ([lielo towtruck](https://gta.fandom.com/wiki/Towtruck_(truck))). Pārveidot 'NPC' darba peļņu, jo šobrīd, ja mehāniķis izvēlas to darīt, visa nopelnītā nauda aiziet uz kompāniju, nevis spēlētājam kabatā.

**Vai šis ieteikums ir saistīts ar kādu problēmu? Lūdzu izkaidro to.**
Delete poga traucē darboties ar flatbed, jo ja paskatās player sarakstu, tad ieslēdzas/izslēdzas darbs, kas uzreiz atzīmē kartē punktu uz kuru jādodas. Mazais towtruck ir gandrīz neaizmantojams, jo no tā bieži nokrīt uzkabinātā automašīna, un āķis velkas pa zemi (npc sāk skriet un bļaustīties)

**Apraksti to ko tu vēlētos redzēt serverī.**
Lielo towtruck, nomainītu npc job pogu un pārtaisītu npc job earning sistēmu. Uzskatu, ka tas dotu mehāniķiem vairāk iespējas roleplayot. It īpaši lielais towtrucks. Kā arī tas atrisinātu problēmu (ja tāda eksistē), ka kāds mehāniķis grindo naudu braukājot uz weed fieldu vai kur citur.

**Vai ir kādas alternatīves iespējas tavam ieteikumam? Kādas?**
Nevaru izdomāt.

**Papildus informācija.**
Ja nemaldos, tad kods (server/main.lua) priekš pārtaisītas npc darba sistēmas izskatīsies šādi -

```
RegisterServerEvent('esx_mechanicjob:onNPCJobMissionCompleted')
AddEventHandler('esx_mechanicjob:onNPCJobMissionCompleted', function()

  local _source = source
  local xPlayer = ESX.GetPlayerFromId(_source)
  local total   = math.random(Config.NPCJobEarnings.min, Config.NPCJobEarnings.max);

  if xPlayer.job.grade >= 3 then
    total = total * 2
  end

    xPlayer.addAccountMoney('bank', total)
  end)

  TriggerClientEvent("esx:showNotification", _source, _U('you_earned').. total)

end)
```

var arī dot naudu uz rokas, kas būtu xPlayer.addMoney(total), lai ('you_earned') strādātu, pie locales jāpievieno ['you_earned'] = 'Tu nopelniji'.
NPC Job peļņu var izmainīt iekš config.lua

Priekš lielā towtrucka, jāpievieno viena rindiņa client/main.lua -

```
            local elements = {
                    {label = _U('flat_bed'), value = 'flatbed'},
                    {label = _U('tow_truck'), value = 'towtruck2'}
(pievienotā)        {label = _U('tow_truck'), value = 'towtruck'}
```

nezinu vai towtruck, vai  towtruck1.

Šaubos vai delete pogu ir grūti nomainīt, tāpēc kodu nerakstīšu (kā arī nezinu, kuras pogas ir brīvas). Kodam vajadzētu būt pareizam, pieņemot to, ka nekas daudz 'esx' nav mainījies.

Also būtu forši ja nomainītu mehāniķa simbola lielumu mapē.

**Comment by Letiix** [comment]
Atļaušos neveidot jaunu postu, bet papildināt šo pašu. 
Iesaku izveidot sistēmu, kurā mehāniķiem tiktu dotas lielākas iespējas un spēlētājiem būtu jāgriežas pie mehāniķiem lai veiktu lielākus darbus savām automašīnām. Ideja sekojoša - Parastajos LS Customs nevar veikt nekādus lielos upgrade (transmisija, motors, suspension utt), bet vietā, kur šobrīd atrodas Bennys Autoserviss (kas netiek izmantots) tiek pievienota iespēju to visu izdarīt, tikai caur mehāniķiem. Mazie darbiņi kā riepu maiņa, krāsas maiņa utt paliek parastajos LS Customs.

**Vai šis ieteikums ir saistīts ar kādu problēmu? Lūdzu izkaidro to. Detalizēts apraksts par problēmu, ja tā pastāv. (Ja nē, rakstam "nē")**
Mazs rp faktors, spēlētājs pats edito savu mašīnu un ne ar vienu cilvēku nesaskarās. 

**Apraksti to ko tu vēlētos redzēt serverī. Vienkārš un skaidrs apraksts par to ko tu vēlētos redzēt serverī. Ja ir iespēja, pievieno linkus vai jebko kas palīdzēs pilnveidot šo ideju.**
Vēlētos redzēt spēlētājus, kas uzlabo savas automašīnas caur mehāniķiem.

**Vai ir kādas alternatīves iespējas tavam ieteikumam? Kādas? Detalizēts apraksts par alternatīvu, ja tāds pastāv. (Ja nē, rakstam "nē")**
Atstāt sistēmu tādu, kāda tā ir tagad.

**Papildus informācija. Jebkāda veida papildus informācija kas varētu palīdzēt izveidot šo ideju, bildes vai video.**
Kā to izdarīt? Pavisam vienkārši, esmu nosūtījis 3omez vecos fivem.lv failus, tajos ir plugins ar nosaukumu esx_bennys. Ieslēdzam pluginu, bet pirmstam editojam dažas lietas,

config.lua nomainam - 

`Config.IsMechanicJobOnly = true` no false, ja mehāniķa darbs main skriptā saucas savādāk, tad, cerams, ka developeri zinās kā visu izmainīt.

```
Config.Zones = {
    ls1 = {
        Pos   = { x = -212.06674194336, y = -1326.6553955078, z = 30.886024475098},
        Size  = {x = 3.0, y = 3.0, z = 0.2},
        Color = {r = 204, g = 204, b = 0},
        Marker= 1,
        Name  = "Autoserviss",
        Hint  = _U('press_custom')
```
pārējās pozīcijas, kas tur atrodas, ja tādas ir aizkomentējam, vai dzēšam, ja ir pārliecība, ka pēc dzēšanas skripts strādās.

Ko darīt ar parastajiem LS Customs? Skriptā aizkomentējam, vai dzēšam rindiņas, kas attiecas uz engine, transmission, suspension etc upgreidiem.

Ja vajadzīga palīdzība, mans discords deviem ir pieejams, ja varēšu, palīdzēšu.

**Comment by xVelns** [comment]
Paldies par detalizēto aprakstu.

Poga no DELETE tika nomainīta uz "L" (pārāk daudz pogas ir aizņemtas, un ir cilvēki kam nav Numpad, tapēc tās pogas netiek gandrīz izmantotas)

Jauni/Custom auto šobrīd netiks pievienoti, tapēc jāiztiek ar to kas ir.

Kā arī Darba izmaksa paliek kāda viņa ir, jo nauda tiek sūtīta uz darbu, pēctam, kad tiks iešķirts Mehāniķu priekšnieks/Boss - viņš varēs izdalīt naudu citiem spēlētājiem.

Kā arī pēc nākamā restarta tiks pievienots klāt Benny's uz pārbaudi vai viss strādās. - Ja strādās, tad upgreidi parastajos LS Customs tiks izņemti.

**Comment by xVelns** [comment]
Paldies par detalizēto aprakstu.

Poga no DELETE tika nomainīta uz "L" (pārāk daudz pogas ir aizņemtas, un ir cilvēki kam nav Numpad, tapēc tās pogas netiek gandrīz izmantotas)

Jauni/Custom auto šobrīd netiks pievienoti, tapēc jāiztiek ar to kas ir.

Kā arī Darba izmaksa paliek kāda viņa ir, jo nauda tiek sūtīta uz darbu, pēctam, kad tiks iešķirts Mehāniķu priekšnieks/Boss - viņš varēs izdalīt naudu citiem spēlētājiem.

Kā arī pēc nākamā restarta tiks pievienots klāt Benny's uz pārbaudi vai viss strādās. - Ja strādās, tad upgreidi parastajos LS Customs tiks izņemti.
