### ISSUE TITLE
[Ieteikums] Menu

### ISSUE THREAD

**Issue by Letiix** [xVelns/IronCountry#4]
**Vai šis ieteikums ir saistīts ar kādu problēmu? Lūdzu izkaidro to.**
Visi menu logi, kas izlec atrodas ekrāna kreisajā, augšējā stūrī. Līdz ar ko tiek bloķēts čats.

**Apraksti to ko tu vēlētos redzēt serverī.**
Visi menu logi tiek pārvietoti uz ekrāna labo, apakšējō stūri, jo tur nekas neatrodas.

**Vai ir kādas alternatīves iespējas tavam ieteikumam? Kādas?**
Nevaru izdomāt.

**Papildus informācija.**
Visur, kur tiek izmantoti menu, nomainīt sekojošo -
`align    = 'top-left',`
uz
`align    = 'bottom-right',`

Kods strādās, pieņemot to, ka 'esx' nekas daudz nav mainījies.

**Comment by xVelns** [comment]
Izmaiņas tika nosūtītas 3omez un tiks ieviestas drīzumā.
