### ISSUE TITLE
[Ieteikums] Pirkt/Pārdot auto

### ISSUE THREAD

**Issue by DatBlacky** [xVelns/IronCountry#5]
Vai šis ieteikums ir saistīts ar kādu problēmu? Jā? Nevar pārdot/nopirkt personai/no personas.

Apraksti to ko tu vēlētos redzēt serverī. Vienkārš un skaidrs apraksts par to ko tu vēlētos redzēt serverī. Ja ir iespēja, pievieno linkus vai jebko kas palīdzēs pilnveidot šo ideju. - Iespēja pārdot auto scrapyard ( NPC ) un iespēja pārdot auto tieši kādam cilvēkam, vēl labāk - izveidot placi, kurā var ievietot savus auto pārdošanai, kur varētu glabāties līdz pat ~20[?] transportlīdzekļiem.

Vai ir kādas alternatīves iespējas tavam ieteikumam? Kādas? Detalizēts apraksts par alternatīvu, ja tāds pastāv. nedomāju.

Papildus informācija. Jebkāda veida papildus informācija kas varētu palīdzēt izveidot šo ideju, bildes vai video. Nedomāju, ka ir vajadzīga.

**Comment by 3omez** [comment]
@DatBlacky Šodien ieviests. :)

**Comment by xVelns** [comment]
@DatBlacky Šodien auto plači līdz 11 transportiem tika ieviesti serverī! :)
Lai labi pārdodas transporti!
