### ISSUE TITLE
[Balansēts ieteikums] High-Ping Kikotājs

### ISSUE THREAD

**Issue by MadFiu** [xVelns/IronCountry#6]
**Apraksti iemeslu šim balansa pieņēmumam. Detalizēts apraksts kas šobrīd notiek un kapēc tev šķiet, ka tas ir negodīgi/nebalansēti.**
Tātad. Nezinu vai tas ir aktuāli arī vēl kādam. Pinga kickotājs labi strādā un tas ir ļoti labi, bet esmu bieži izkickots tikai vien tā dēļ, ka uz kādu sekundi man uzlec virs 400 pings un tieku kickots. Man provideris mēdz tā darīt un es tur nevaru neko iesākt, dzīvodams kojās. Tā jau internets ir normāls un pavelk visu. Vienkārši ir tie mistiskie "uzsekundi500-700pings".
**Apraksti savu ideju kā to izbalansēt. Detalizēts apraksts ko tu vēlētos panākt.**
To Kikotāju varētu pielāgot tā, lai viņš nekicko automātiski, kad spēlētājs uzreiz sasniedz to robežu, bet tieši lai kicko, ja pings ir ilgāk (like kādas 2-3sec). 
Protams, šis var radīt Mēness neredzamo pusi, kur kādam nelaimīgajam var būt stabili 300ping un vairāk, kas nemainās (kāds ārzemnieks vai lauku nomaļnieks ar sliktu tīklu), kas var izsist serveri no sliedēm vai taml.
Anyway, tā ir itkā mana problēma, ka nets karās, bet šāda sistēma varētu mazināt galvassāpes kādam, kas ir dziļi Roleplayā un viņu izkicko. (ja vēl kādam ir tāda problēma)

**Papildus informācija. Jebkāda veida papildus informācija vai ideja, kas varētu palīdzēt balansēt serveri.**
Diemžēl nevarēšu papildus informāciju sniegt.

**Comment by xVelns** [comment]
Ping limits šobrīd ir 650 un pinga pārbaude tika uztaisīta mazliet ilgāka, tādējādi samazinot izmešanas iespēju, ja tomēr tevi vel met ārā, lūdzu vērsties #čats
