### ISSUE TITLE
[Ieteikums/Balanss] Auto un vispārīgi.

### ISSUE THREAD

**Issue by DatBlacky** [xVelns/IronCountry#7]
Apraksti iemeslu šim balansa pieņēmumam. Detalizēts apraksts kas šobrīd notiek un kapēc tev šķiet, ka tas ir negodīgi/nebalansēti. 
1. Automašīnu degvielas patēriņš ir jāsamazina, jo apbraucot apkārt visam Los Santos 70% bākas ir pārvērtušies par 6%, kas nav normāli, jo tie nav vairāk kā 10km un pa 10km automašīnas bākas nav tukšas.
2. Atrodoties automašīnā varētu uzrādīt indikatoru, ka neesi piesprādzējies, jo dažkārt to sanāk piemirst un tas izraisa ļoti lielas problēmas. Un IRL mūsdienu automašīnas vienmēr atgādina šoferiem par šo, tāpēc tas būtu tikai vēl viens veids kā veidot realistiskāku serveri.
3. Izņemt to Ali Bomaye dziesmu no loading screen, jo nepietiek ar to, ka FiveM paši izdomājuši uzlikt soundtracku ieejot viņu launcheri, vēl man ir jāklausās 2013. gadā atklausīta dziesma.. Ja neizņemat, tad vismaz iespēju pašam to ieslēgt/izslēgt/samazināt skaļumu.

Apraksti savu ideju kā to izbalansēt. Detalizēts apraksts ko tu vēlētos panākt. - Augstāk viss ir.

Papildus informācija. Jebkāda veida papildus informācija vai ideja, kas varētu palīdzēt balansēt serveri. - Augstāk viss ir.

**Comment by xVelns** [comment]
1. Patēriņš tiek "mērīts" pēc apgriezienu daudzuma = Lielāks RPM = Vairāk degvielas.
2. Šis bija ielikts taču josta nenostrādāja. Iespējams tiks ieviests nākotnē! (soonTM)
3. Dziesma šobrīd paliek, taču ja ir kāda specifiska vēlme pēc mūzika iekšs menu, to var apspriest #čats

**Comment by xVelns** [comment]
Atjauninājums 2. punktam:

Ir ielikts vizuāls jostas atgādinājums/norādījums auto kā arī vai ir ieslēgta kruīza kontrole. Paldies par ieteikumu. <3
