### ISSUE TITLE
[Ieteikums] Noteikumu papildināšana.

### ISSUE THREAD

**Issue by RedlineLV** [xVelns/IronCountry#8]
Vai šis ieteikums ir saistīts ar kādu problēmu? Saistīts ar noteikumu papildināšanu.

Apraksti to ko tu vēlētos redzēt serverī. Vienkārš un skaidrs apraksts par to ko tu vēlētos redzēt serverī. Ja ir iespēja, pievieno linkus vai jebko kas palīdzēs pilnveidot šo ideju. - Manuprāt vajadzētu izveidot noteikumus, ka nedrīkst būt gan policists, gan nelegālais, proti, ar vienu charu būt par policistu, ar otru par nelegālo. **Manuprāt šis noteikums samazinātu MG iespējamību**, lai netiktu nodots policistu plāns savam nelegālajam grupējumam.

Papildus informācija. Jebkāda veida papildus informācija kas varētu palīdzēt izveidot šo ideju, bildes vai video. Nav nepieciešams, ieteikums balstās un noteikumu pilnveidošanas, lai RP attīstu pēc iespējas reālāk. 

**P.S. Ir līdzīgs noteikums - "Ja esi valsts nolīgts darbinieks, darboties nelegālajā sfērā ir aizliegts!" bet var saprast divējādi, ka ar to pašu charu nedrīkst darboties nelegālajā sfērā vai ar otru charu.
Ja tas noteikums balstās uz manu ieteikumu, tad ieteiktu drusku pārveidot, lai citiem nerastos pārpratumi.
Bet ja tas balstās uz to, ka nedrīkst ar to pašu charu atrasties policistos un tajā pašā laikā darboties ar nelegālajiem, tad samainīt to kā par aizliegumu uz korumpētību.**

**Comment by xVelns** [comment]
Paldies, RedlineLV par ieteikumu.

Parunājoties ar Deviem un Adminu, ir nolemts, ka cilvēki var būt arī nelegālā sfērā, ja esi legālā vai Valsts darbinieks.
Tapēc esot likts iekšā šis Multi-Character scripts un lai spētu RP`ot no sirds.
Varbūt, lai nerastos tik liels metagaming arī no pašu pusēm, nevajadzētu uzticēties katram cilvēkam un izpausts katru nelegālo darbu vietas. (Dzīvē tu arī nestāstīšu svešiniekam kuru pazīsti pāris dienas, kur pārdod metanfetamīnu :D )

Šobrīd šis ir galējais lēmums no Administrācijas, taču, ja kaut kas mainīsies - būs noteikti paziņots.

Labu vēlot,
xVelns
