### ISSUE TITLE
PF / CCW 

### ISSUE THREAD

**Issue by Edgars9270** [xVelns/IronCountry#9]
Mana ideja ir šāda - ieviest jauna veida licenzes jo tagad ieročus var iegūt kurš katrs.
Ir diva veida licenzes
Privātais ierocis ( PF jeb Personal Firearm )
Pārnēsājamā ieroča licenze ( CCW jeb Carry Concealed Weapon ) 

Personīgā ieroča licenze atļaus tev iegādāties šo ieroci, tu viņus varēsi turēt iekš biznesa/mājas utml. Ja tiksi noķerts ar šo ieroci tiksi sodīts ar licenzes atņemšanu un brīvības atņemšanu .
Pārnēsājamā ieroča licenze atļaus ieroci nēsāt ikdienā kā pašaisardzības līdzekli. Problēmas varēs sanākt tikai gadījumā ja izmantosi kriminālos nolūkos.

Lai iegūtu privāto ieroču licenzi - Mans uzskats būtu jāsamaksā noteikts naudas daudzums ( 10.000$ ?) , jābūt 21 gadus vecam ( in game ), un uzskatu ka vajadzētu rakstīt pieteikumu uz šo licenzi , kā arī protams nedrīkstētu tikt sodīts un iespējams un jāveic psihoterapijas pārbaude? ( nāktu klāt jauns darbs -psihoterapeits ?) 

Lai iegūtu pārnēsājamo ieroču licenzi - Tu vari iegūt tikai ja esi bijis nesodīts, jāsamaksā naudas summa ( 20,000$ ?), 21 gadus vecam ( in game ) , jābūt PF licenzei. Lai iegūtu šo licenzi būtu jāraksta vēlviens pieteikums.

Domāju ka šis būtu vairāk realistiskāks veids kā iegūt ieroci, nevis nopērkot licenzi un ieroci.

**Comment by xVelns** [comment]
Doma laba, taču ar šobrīd esošo ieroču licenses sistēmu, šo licenzi nevar vienkārši piešķirt diemžēl.
Ja tiks mainīta ieroču un to licenšu sistēma uz ko labāku par to tiks ziņots un varēsim uzklausīt arī jūs idejas par viņu.

Nākotnē lūgums izmantot esošos template/paraugus kā sastādīt pareizi ieteikumu.

Paldies! <3
